# Application configuration
image:
  repository: python-webapp
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort  # Changed from LoadBalancer for GitHub Actions
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

# Environment configuration
config:
  database_url: "sqlite:///./books.db"
  app_environment: "production"

secrets:
  api_key: "your-secret-key"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 40  # Increased delay
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 30  # Increased delay
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3