name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest pytest-cov

    # Build local image only
    - name: Build Docker image
      run: |
        docker build -t python-webapp:${{ github.sha }} ./app
        docker build -t python-webapp:latest ./app

    # Container registry steps commented out for local development
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #
    # - name: Push Docker image
    #   run: |
    #     docker tag python-webapp:${{ github.sha }} ghcr.io/${{ github.repository }}/python-webapp:${{ github.sha }}
    #     docker push ghcr.io/${{ github.repository }}/python-webapp:${{ github.sha }}